apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # TOTO JE JEN VZOR (Do Gitu nikdy necommitujeme reálná hesla)
  DB_USER: "tady_bude_uzivatel"
  DB_PASSWORD: "tady_bude_heslo"